import test from 'node:test';
import assert from 'node:assert/strict';
import { downloadVideo } from '../modules/video-output.js';

test('a rejected Chrome download cannot be reported as a completed product', async () => {
  globalThis.chrome = {
    storage: {sync:{get:async()=>({settings:{}})}},
    runtime: {sendMessage:async()=>({ok:true,downloadId:null,downloadError:'Download canceled'})},
  };
  await assert.rejects(downloadVideo('data:video/mp4;base64,dGVzdA==',{productId:'boots'}), /Download canceled/);
});

test('a successful download uses the actual generated bytes and product filename', async () => {
  const url = 'data:video/mp4;base64,dGVzdA==';
  let request;
  globalThis.chrome = {
    storage: {sync:{get:async()=>({settings:{}})}},
    runtime: {sendMessage:async message=>{request=message;return {ok:true,downloadId:123,videoUrl:url,mimeType:'video/mp4'};}},
  };
  const result = await downloadVideo(url,{productId:'boots'});
  assert.equal(request.type,'DOWNLOAD_VIDEO');
  assert.equal(request.payload.url,url);
  assert.match(request.payload.filename,/^boots_\d{4}-\d{2}-\d{2}_tiktok\.mp4$/);
  assert.equal(result.downloadId,123);
});
